# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test JavaScrip excercises

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testJavaScript:
    name: Test JavaScript excercises
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    - name: Run npm test in exercise folders
      run: |
          cd javascript/
          for dir in $(find . -type d -name 'node_modules' -prune -o -type d -print); do
          if [ -f "$dir/package.json" ]; then
              echo "Running npm install in $dir"
              (cd "$dir" && npm i && npm run build --if-present && npm test)
          fi
          done
