# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test C# excercises

on: [ pull_request,"push" ]

jobs:
  testCSharp:
    name: Test C# excercises
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./csharp
    - name: Build
      run: dotnet build ./csharp --no-restore
    - name: Test
      run: dotnet test ./csharp --no-build --verbosity normal